sudo: required

services:
  - docker

env:
  global:
    - QUASSELCORE_VERSION=${QUASSELCORE_VERSION:-0.13.0}
    - BUILD_DATE=$(date +"%Y-%m-%d")
    - BUILD_TYPE=stable

jobs:
  include:
    - stage: build
      script:
        - make

    - stage: build and test
      script:
        - make
        - make compose-file
        - docker-compose build
        - docker-compose up -d
        - make test
        - docker-compose kill
        - docker-compose down

    - stage: push latest docker image
      script:
        - make
        - docker login -u="${DOCKER_USERNAME}" -p="${DOCKER_PASSWORD}"
        #
        - docker tag  ${USER}/quassel-core:latest ${DOCKER_USERNAME}/docker-quassel-core:latest
        - docker push ${DOCKER_USERNAME}/docker-quassel-core:latest
        #
        - docker tag  ${DOCKER_USERNAME}/docker-quassel-core:latest ${DOCKER_USERNAME}/docker-quassel-core:${QUASSELCORE_VERSION}
        - docker push ${DOCKER_USERNAME}/docker-quassel-core:${QUASSELCORE_VERSION}
        #
        - docker logout
