sudo: required

services:
  - docker

env:
  global:
    - QUASSELCORE_VERSION=${QUASSELCORE_VERSION:-0.13.0}
    - BUILD_DATE=$(date +"%Y-%m-%d")
    - BUILD_TYPE=stable

jobs:
  include:
    - stage: build
      script:
        - make

