#!/bin/bash

# Custom build for Docker Hub
# see: https://medium.com/microscaling-systems/labelling-automated-builds-on-docker-hub-f3d073fb8e1

[[ -e hooks/environment ]] && . hooks/environment

cat << EOF >> .env
BUILD_DATE=${BUILD_DATE}
BUILD_VERSION=${BUILD_VERSION}
BUILD_TYPE=${BUILD_TYPE}

QUASSELCORE_VERSION=${QUASSELCORE_VERSION}
QUASSELCORE_LOGLEVEL=Debug

QUASSEL_HOST=quassel-core
QUASSEL_PORT=4242

WEBSERVER_MODE=http
EOF

docker-compose \
  --file docker-compose_example.yml \
  config > docker-compose.yml
